apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-helloworld-staging 
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values-staging.yaml 
    path: manifests/helm
    repoURL: https://github.com/jbravo94/python-helloworld 
    targetRevision: HEAD
