apiVersion: v1
data:
  version: {{ .Values.image.tag }}
kind: ConfigMap
metadata:
  name: {{ .Values.image.repository }}-version
  namespace: {{ .Values.namespace.name }}
data:
  {{ .Values.configmap.data }}
